export type ClueTier = 'beginner' | 'easy' | 'medium' | 'hard' | 'elite' | 'master';

/**
 * Direct-hotlink URLs for item images hosted on the OSRS Wiki.
 * We do not store item PNGs in this repo, only the URLs to them.
 * Source: https://oldschool.runescape.wiki
 */
export class WikiItemImages {
  private static readonly BASE_URL = 'https://oldschool.runescape.wiki/images';

  // Home page
  static readonly THIRD_AGE_PICKAXE = `${WikiItemImages.BASE_URL}/3rd_age_pickaxe.png`;
  static readonly RANGER_BOOTS = `${WikiItemImages.BASE_URL}/Ranger_boots.png`;
  static readonly ROBIN_HOOD_HAT = `${WikiItemImages.BASE_URL}/Robin_hood_hat.png`;
  static readonly GILDED_PLATEBODY = `${WikiItemImages.BASE_URL}/Gilded_platebody.png`;
  static readonly DRAGON_BOOTS = `${WikiItemImages.BASE_URL}/Dragon_boots.png`;
  static readonly CLUE_SCROLL_MASTER = `${WikiItemImages.BASE_URL}/Clue_scroll_(master).png`;
  static readonly REWARD_CASKET_HARD = `${WikiItemImages.BASE_URL}/Reward_casket_(hard).png`;
  static readonly REWARD_CASKET_MASTER = `${WikiItemImages.BASE_URL}/Reward_casket_(master).png`;

  /** Reward casket image, keyed by tier. */
  static readonly REWARD_CASKETS: Record<ClueTier, string> = {
    beginner: `${WikiItemImages.BASE_URL}/Reward_casket_(beginner).png`,
    easy: `${WikiItemImages.BASE_URL}/Reward_casket_(easy).png`,
    medium: `${WikiItemImages.BASE_URL}/Reward_casket_(medium).png`,
    hard: WikiItemImages.REWARD_CASKET_HARD,
    elite: `${WikiItemImages.BASE_URL}/Reward_casket_(elite).png`,
    master: WikiItemImages.REWARD_CASKET_MASTER,
  };

  // Clue scroll rewards, organized by casket tier. Keyed by the item's
  // exact in-game name so callers can look up an image directly from a
  // ClueScrollHelper reward name.
  /** Beginner clue scroll rewards (74 items). */
  static readonly BEGINNER: Record<string, string> = {
    'Mole slippers': `${WikiItemImages.BASE_URL}/Mole_slippers.png`,
    'Frog slippers': `${WikiItemImages.BASE_URL}/Frog_slippers.png`,
    'Bear feet': `${WikiItemImages.BASE_URL}/Bear_feet.png`,
    'Demon feet': `${WikiItemImages.BASE_URL}/Demon_feet.png`,
    'Jester cape': `${WikiItemImages.BASE_URL}/Jester_cape.png`,
    'Shoulder parrot': `${WikiItemImages.BASE_URL}/Shoulder_parrot.png`,
    'Monk\'s robe top (t)': `${WikiItemImages.BASE_URL}/Monk's_robe_top_(t).png`,
    'Monk\'s robe (t)': `${WikiItemImages.BASE_URL}/Monk's_robe_(t).png`,
    'Amulet of defence (t)': `${WikiItemImages.BASE_URL}/Amulet_of_defence_(t).png`,
    'Sandwich lady hat': `${WikiItemImages.BASE_URL}/Sandwich_lady_hat.png`,
    'Sandwich lady top': `${WikiItemImages.BASE_URL}/Sandwich_lady_top.png`,
    'Sandwich lady bottom': `${WikiItemImages.BASE_URL}/Sandwich_lady_bottom.png`,
    'Rune scimitar ornament kit (guthix)': `${WikiItemImages.BASE_URL}/Rune_scimitar_ornament_kit_(guthix).png`,
    'Rune scimitar ornament kit (saradomin)': `${WikiItemImages.BASE_URL}/Rune_scimitar_ornament_kit_(saradomin).png`,
    'Rune scimitar ornament kit (zamorak)': `${WikiItemImages.BASE_URL}/Rune_scimitar_ornament_kit_(zamorak).png`,
    'Cabbage': `${WikiItemImages.BASE_URL}/Cabbage.png`,
    'Black 2h sword': `${WikiItemImages.BASE_URL}/Black_2h_sword.png`,
    'Black axe': `${WikiItemImages.BASE_URL}/Black_axe.png`,
    'Black battleaxe': `${WikiItemImages.BASE_URL}/Black_battleaxe.png`,
    'Black chainbody': `${WikiItemImages.BASE_URL}/Black_chainbody.png`,
    'Black dagger': `${WikiItemImages.BASE_URL}/Black_dagger.png`,
    'Black full helm': `${WikiItemImages.BASE_URL}/Black_full_helm.png`,
    'Black kiteshield': `${WikiItemImages.BASE_URL}/Black_kiteshield.png`,
    'Black longsword': `${WikiItemImages.BASE_URL}/Black_longsword.png`,
    'Black mace': `${WikiItemImages.BASE_URL}/Black_mace.png`,
    'Black med helm': `${WikiItemImages.BASE_URL}/Black_med_helm.png`,
    'Black pickaxe': `${WikiItemImages.BASE_URL}/Black_pickaxe.png`,
    'Black platebody': `${WikiItemImages.BASE_URL}/Black_platebody.png`,
    'Black plateskirt': `${WikiItemImages.BASE_URL}/Black_plateskirt.png`,
    'Black platelegs': `${WikiItemImages.BASE_URL}/Black_platelegs.png`,
    'Black sq shield': `${WikiItemImages.BASE_URL}/Black_sq_shield.png`,
    'Black scimitar': `${WikiItemImages.BASE_URL}/Black_scimitar.png`,
    'Black sword': `${WikiItemImages.BASE_URL}/Black_sword.png`,
    'Black warhammer': `${WikiItemImages.BASE_URL}/Black_warhammer.png`,
    'Shortbow': `${WikiItemImages.BASE_URL}/Shortbow.png`,
    'Longbow': `${WikiItemImages.BASE_URL}/Longbow.png`,
    'Oak shortbow': `${WikiItemImages.BASE_URL}/Oak_shortbow.png`,
    'Oak longbow': `${WikiItemImages.BASE_URL}/Oak_longbow.png`,
    'Iron pickaxe': `${WikiItemImages.BASE_URL}/Iron_pickaxe.png`,
    'Staff of air': `${WikiItemImages.BASE_URL}/Staff_of_air.png`,
    'Staff of water': `${WikiItemImages.BASE_URL}/Staff_of_water.png`,
    'Staff of earth': `${WikiItemImages.BASE_URL}/Staff_of_earth.png`,
    'Staff of fire': `${WikiItemImages.BASE_URL}/Staff_of_fire.png`,
    'Steel full helm': `${WikiItemImages.BASE_URL}/Steel_full_helm.png`,
    'Steel platebody': `${WikiItemImages.BASE_URL}/Steel_platebody.png`,
    'Steel platelegs': `${WikiItemImages.BASE_URL}/Steel_platelegs.png`,
    'Steel plateskirt': `${WikiItemImages.BASE_URL}/Steel_plateskirt.png`,
    'Steel longsword': `${WikiItemImages.BASE_URL}/Steel_longsword.png`,
    'Steel dagger': `${WikiItemImages.BASE_URL}/Steel_dagger.png`,
    'Steel axe': `${WikiItemImages.BASE_URL}/Steel_axe.png`,
    'Steel battleaxe': `${WikiItemImages.BASE_URL}/Steel_battleaxe.png`,
    'Leather cowl': `${WikiItemImages.BASE_URL}/Leather_cowl.png`,
    'Leather body': `${WikiItemImages.BASE_URL}/Leather_body.png`,
    'Leather chaps': `${WikiItemImages.BASE_URL}/Leather_chaps.png`,
    'Leather vambraces': `${WikiItemImages.BASE_URL}/Leather_vambraces.png`,
    'Hardleather body': `${WikiItemImages.BASE_URL}/Hardleather_body.png`,
    'Blue wizard hat': `${WikiItemImages.BASE_URL}/Blue_wizard_hat.png`,
    'Blue wizard robe': `${WikiItemImages.BASE_URL}/Blue_wizard_robe.png`,
    'Wizard hat': `${WikiItemImages.BASE_URL}/Wizard_hat.png`,
    'Black robe': `${WikiItemImages.BASE_URL}/Black_robe.png`,
    'Air rune': `${WikiItemImages.BASE_URL}/Air_rune.png`,
    'Mind rune': `${WikiItemImages.BASE_URL}/Mind_rune.png`,
    'Water rune': `${WikiItemImages.BASE_URL}/Water_rune.png`,
    'Earth rune': `${WikiItemImages.BASE_URL}/Earth_rune.png`,
    'Fire rune': `${WikiItemImages.BASE_URL}/Fire_rune.png`,
    'Body rune': `${WikiItemImages.BASE_URL}/Body_rune.png`,
    'Chaos rune': `${WikiItemImages.BASE_URL}/Chaos_rune.png`,
    'Nature rune': `${WikiItemImages.BASE_URL}/Nature_rune.png`,
    'Law rune': `${WikiItemImages.BASE_URL}/Law_rune.png`,
    'Bronze arrow': `${WikiItemImages.BASE_URL}/Bronze_arrow_detail.png`,
    'Iron arrow': `${WikiItemImages.BASE_URL}/Iron_arrow_detail.png`,
    'Shrimps': `${WikiItemImages.BASE_URL}/Shrimps.png`,
    'Sardine': `${WikiItemImages.BASE_URL}/Sardine.png`,
    'Herring': `${WikiItemImages.BASE_URL}/Herring.png`,
  };

  /** Easy clue scroll rewards (87 items). */
  static readonly EASY: Record<string, string> = {
    'Willow comp bow': `${WikiItemImages.BASE_URL}/Willow_comp_bow.png`,
    'Amulet of magic (t)': `${WikiItemImages.BASE_URL}/Amulet_of_magic_(t).png`,
    'Wooden shield (g)': `${WikiItemImages.BASE_URL}/Wooden_shield_(g).png`,
    'Black full helm (t)': `${WikiItemImages.BASE_URL}/Black_full_helm_(t).png`,
    'Black platebody (t)': `${WikiItemImages.BASE_URL}/Black_platebody_(t).png`,
    'Black platelegs (t)': `${WikiItemImages.BASE_URL}/Black_platelegs_(t).png`,
    'Steel full helm (t)': `${WikiItemImages.BASE_URL}/Steel_full_helm_(t).png`,
    'Steel platebody (t)': `${WikiItemImages.BASE_URL}/Steel_platebody_(t).png`,
    'Iron full helm (t)': `${WikiItemImages.BASE_URL}/Iron_full_helm_(t).png`,
    'Iron platebody (t)': `${WikiItemImages.BASE_URL}/Iron_platebody_(t).png`,
    'Black full helm (g)': `${WikiItemImages.BASE_URL}/Black_full_helm_(g).png`,
    'Black platebody (g)': `${WikiItemImages.BASE_URL}/Black_platebody_(g).png`,
    'Black platelegs (g)': `${WikiItemImages.BASE_URL}/Black_platelegs_(g).png`,
    'Black shield (h1)': `${WikiItemImages.BASE_URL}/Black_shield_(h1).png`,
    'Black helm (h1)': `${WikiItemImages.BASE_URL}/Black_helm_(h1).png`,
    'Flared trousers': `${WikiItemImages.BASE_URL}/Flared_trousers.png`,
    'Black cane': `${WikiItemImages.BASE_URL}/Black_cane.png`,
    'Staff of bob the cat': `${WikiItemImages.BASE_URL}/Staff_of_bob_the_cat.png`,
    'Amulet of power (t)': `${WikiItemImages.BASE_URL}/Amulet_of_power_(t).png`,
    'Ham joint': `${WikiItemImages.BASE_URL}/Ham_joint.png`,
    'Rain bow': `${WikiItemImages.BASE_URL}/Rain_bow.png`,
    'Leather body (g)': `${WikiItemImages.BASE_URL}/Leather_body_(g).png`,
    'Blue wizard hat (g)': `${WikiItemImages.BASE_URL}/Blue_wizard_hat_(g).png`,
    'Blue wizard robe (g)': `${WikiItemImages.BASE_URL}/Blue_wizard_robe_(g).png`,
    'Black wizard hat (g)': `${WikiItemImages.BASE_URL}/Black_wizard_hat_(g).png`,
    'Black wizard robe (g)': `${WikiItemImages.BASE_URL}/Black_wizard_robe_(g).png`,
    'Saradomin robe top': `${WikiItemImages.BASE_URL}/Saradomin_robe_top.png`,
    'Guthix robe top': `${WikiItemImages.BASE_URL}/Guthix_robe_top.png`,
    'Zamorak robe top': `${WikiItemImages.BASE_URL}/Zamorak_robe_top.png`,
    'Ancient robe top': `${WikiItemImages.BASE_URL}/Ancient_robe_top.png`,
    'Armadyl robe top': `${WikiItemImages.BASE_URL}/Armadyl_robe_top.png`,
    'Bandos robe top': `${WikiItemImages.BASE_URL}/Bandos_robe_top.png`,
    'Bob\'s red shirt': `${WikiItemImages.BASE_URL}/Bob's_red_shirt.png`,
    'Highwayman mask': `${WikiItemImages.BASE_URL}/Highwayman_mask.png`,
    'Blue beret': `${WikiItemImages.BASE_URL}/Blue_beret.png`,
    'Black beret': `${WikiItemImages.BASE_URL}/Black_beret.png`,
    'A powdered wig': `${WikiItemImages.BASE_URL}/A_powdered_wig.png`,
    'Beanie': `${WikiItemImages.BASE_URL}/Beanie.png`,
    'Imp mask': `${WikiItemImages.BASE_URL}/Imp_mask.png`,
    'Goblin mask': `${WikiItemImages.BASE_URL}/Goblin_mask.png`,
    'Sleeping cap': `${WikiItemImages.BASE_URL}/Sleeping_cap.png`,
    'Golden chef\'s hat': `${WikiItemImages.BASE_URL}/Golden_chef's_hat.png`,
    'Golden apron': `${WikiItemImages.BASE_URL}/Golden_apron.png`,
    'Red elegant shirt': `${WikiItemImages.BASE_URL}/Red_elegant_shirt.png`,
    'Team cape zero': `${WikiItemImages.BASE_URL}/Team_cape_zero.png`,
    'Team cape i': `${WikiItemImages.BASE_URL}/Team_cape_i.png`,
    'Team cape x': `${WikiItemImages.BASE_URL}/Team_cape_x.png`,
    'Cape of skulls': `${WikiItemImages.BASE_URL}/Cape_of_skulls.png`,
    'Monk\'s robe top (g)': `${WikiItemImages.BASE_URL}/Monk's_robe_top_(g).png`,
    'Monk\'s robe (g)': `${WikiItemImages.BASE_URL}/Monk's_robe_(g).png`,
    'Black full helm': `${WikiItemImages.BASE_URL}/Black_full_helm.png`,
    'Black platebody': `${WikiItemImages.BASE_URL}/Black_platebody.png`,
    'Black platelegs': `${WikiItemImages.BASE_URL}/Black_platelegs.png`,
    'Black longsword': `${WikiItemImages.BASE_URL}/Black_longsword.png`,
    'Black battleaxe': `${WikiItemImages.BASE_URL}/Black_battleaxe.png`,
    'Black axe': `${WikiItemImages.BASE_URL}/Black_axe.png`,
    'Black dagger': `${WikiItemImages.BASE_URL}/Black_dagger.png`,
    'Steel pickaxe': `${WikiItemImages.BASE_URL}/Steel_pickaxe.png`,
    'Black pickaxe': `${WikiItemImages.BASE_URL}/Black_pickaxe.png`,
    'Coif': `${WikiItemImages.BASE_URL}/Coif.png`,
    'Studded body': `${WikiItemImages.BASE_URL}/Studded_body.png`,
    'Studded chaps': `${WikiItemImages.BASE_URL}/Studded_chaps.png`,
    'Willow shortbow': `${WikiItemImages.BASE_URL}/Willow_shortbow.png`,
    'Staff of air': `${WikiItemImages.BASE_URL}/Staff_of_air.png`,
    'Willow longbow': `${WikiItemImages.BASE_URL}/Willow_longbow.png`,
    'Amulet of magic': `${WikiItemImages.BASE_URL}/Amulet_of_magic.png`,
    'Air rune': `${WikiItemImages.BASE_URL}/Air_rune.png`,
    'Mind rune': `${WikiItemImages.BASE_URL}/Mind_rune.png`,
    'Water rune': `${WikiItemImages.BASE_URL}/Water_rune.png`,
    'Earth rune': `${WikiItemImages.BASE_URL}/Earth_rune.png`,
    'Fire rune': `${WikiItemImages.BASE_URL}/Fire_rune.png`,
    'Body rune': `${WikiItemImages.BASE_URL}/Body_rune.png`,
    'Chaos rune': `${WikiItemImages.BASE_URL}/Chaos_rune.png`,
    'Nature rune': `${WikiItemImages.BASE_URL}/Nature_rune.png`,
    'Law rune': `${WikiItemImages.BASE_URL}/Law_rune.png`,
    'Trout': `${WikiItemImages.BASE_URL}/Trout.png`,
    'Salmon': `${WikiItemImages.BASE_URL}/Salmon.png`,
    'Coins': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Master scroll book (empty)': `${WikiItemImages.BASE_URL}/Master_scroll_book_(empty).png`,
    'Saradomin page 1': `${WikiItemImages.BASE_URL}/Saradomin_page_1.png`,
    'Zamorak page 1': `${WikiItemImages.BASE_URL}/Zamorak_page_1.png`,
    'Guthix page 1': `${WikiItemImages.BASE_URL}/Guthix_page_1.png`,
    'Bandos page 1': `${WikiItemImages.BASE_URL}/Bandos_page_1.png`,
    'Armadyl page 1': `${WikiItemImages.BASE_URL}/Armadyl_page_1.png`,
    'Ancient page 1': `${WikiItemImages.BASE_URL}/Ancient_page_1.png`,
    'Clue scroll (master)': `${WikiItemImages.BASE_URL}/Clue_scroll_(master).png`,
  };

  /** Medium clue scroll rewards (193 items). */
  static readonly MEDIUM: Record<string, string> = {
    'Gnomish firelighter': `${WikiItemImages.BASE_URL}/Gnomish_firelighter.png`,
    'Yew comp bow': `${WikiItemImages.BASE_URL}/Yew_comp_bow.png`,
    'Strength amulet (t)': `${WikiItemImages.BASE_URL}/Strength_amulet_(t).png`,
    'Ranger boots': `${WikiItemImages.BASE_URL}/Ranger_boots.png`,
    'Wizard boots': `${WikiItemImages.BASE_URL}/Wizard_boots.png`,
    'Holy sandals': `${WikiItemImages.BASE_URL}/Holy_sandals.png`,
    'Spiked manacles': `${WikiItemImages.BASE_URL}/Spiked_manacles.png`,
    'Climbing boots (g)': `${WikiItemImages.BASE_URL}/Climbing_boots_(g).png`,
    'Adamant full helm (t)': `${WikiItemImages.BASE_URL}/Adamant_full_helm_(t).png`,
    'Adamant platebody (t)': `${WikiItemImages.BASE_URL}/Adamant_platebody_(t).png`,
    'Adamant platelegs (t)': `${WikiItemImages.BASE_URL}/Adamant_platelegs_(t).png`,
    'Adamant plateskirt (t)': `${WikiItemImages.BASE_URL}/Adamant_plateskirt_(t).png`,
    'Adamant kiteshield (t)': `${WikiItemImages.BASE_URL}/Adamant_kiteshield_(t).png`,
    'Adamant full helm (g)': `${WikiItemImages.BASE_URL}/Adamant_full_helm_(g).png`,
    'Adamant platebody (g)': `${WikiItemImages.BASE_URL}/Adamant_platebody_(g).png`,
    'Adamant platelegs (g)': `${WikiItemImages.BASE_URL}/Adamant_platelegs_(g).png`,
    'Adamant plateskirt (g)': `${WikiItemImages.BASE_URL}/Adamant_plateskirt_(g).png`,
    'Adamant kiteshield (g)': `${WikiItemImages.BASE_URL}/Adamant_kiteshield_(g).png`,
    'Adamant shield (h1)': `${WikiItemImages.BASE_URL}/Adamant_shield_(h1).png`,
    'Adamant shield (h2)': `${WikiItemImages.BASE_URL}/Adamant_shield_(h2).png`,
    'Adamant shield (h3)': `${WikiItemImages.BASE_URL}/Adamant_shield_(h3).png`,
    'Adamant shield (h4)': `${WikiItemImages.BASE_URL}/Adamant_shield_(h4).png`,
    'Adamant shield (h5)': `${WikiItemImages.BASE_URL}/Adamant_shield_(h5).png`,
    'Adamant helm (h1)': `${WikiItemImages.BASE_URL}/Adamant_helm_(h1).png`,
    'Adamant helm (h2)': `${WikiItemImages.BASE_URL}/Adamant_helm_(h2).png`,
    'Adamant helm (h3)': `${WikiItemImages.BASE_URL}/Adamant_helm_(h3).png`,
    'Adamant helm (h4)': `${WikiItemImages.BASE_URL}/Adamant_helm_(h4).png`,
    'Adamant helm (h5)': `${WikiItemImages.BASE_URL}/Adamant_helm_(h5).png`,
    'Adamant platebody (h1)': `${WikiItemImages.BASE_URL}/Adamant_platebody_(h1).png`,
    'Adamant platebody (h2)': `${WikiItemImages.BASE_URL}/Adamant_platebody_(h2).png`,
    'Adamant platebody (h3)': `${WikiItemImages.BASE_URL}/Adamant_platebody_(h3).png`,
    'Adamant platebody (h4)': `${WikiItemImages.BASE_URL}/Adamant_platebody_(h4).png`,
    'Adamant platebody (h5)': `${WikiItemImages.BASE_URL}/Adamant_platebody_(h5).png`,
    'Mithril full helm (g)': `${WikiItemImages.BASE_URL}/Mithril_full_helm_(g).png`,
    'Mithril platebody (g)': `${WikiItemImages.BASE_URL}/Mithril_platebody_(g).png`,
    'Mithril platelegs (g)': `${WikiItemImages.BASE_URL}/Mithril_platelegs_(g).png`,
    'Mithril plateskirt (g)': `${WikiItemImages.BASE_URL}/Mithril_plateskirt_(g).png`,
    'Mithril kiteshield (g)': `${WikiItemImages.BASE_URL}/Mithril_kiteshield_(g).png`,
    'Mithril full helm (t)': `${WikiItemImages.BASE_URL}/Mithril_full_helm_(t).png`,
    'Mithril platebody (t)': `${WikiItemImages.BASE_URL}/Mithril_platebody_(t).png`,
    'Mithril platelegs (t)': `${WikiItemImages.BASE_URL}/Mithril_platelegs_(t).png`,
    'Mithril plateskirt (t)': `${WikiItemImages.BASE_URL}/Mithril_plateskirt_(t).png`,
    'Mithril kiteshield (t)': `${WikiItemImages.BASE_URL}/Mithril_kiteshield_(t).png`,
    'Green d\'hide body (g)': `${WikiItemImages.BASE_URL}/Green_d'hide_body_(g).png`,
    'Green d\'hide body (t)': `${WikiItemImages.BASE_URL}/Green_d'hide_body_(t).png`,
    'Green d\'hide chaps (g)': `${WikiItemImages.BASE_URL}/Green_d'hide_chaps_(g).png`,
    'Green d\'hide chaps (t)': `${WikiItemImages.BASE_URL}/Green_d'hide_chaps_(t).png`,
    'Saradomin mitre': `${WikiItemImages.BASE_URL}/Saradomin_mitre.png`,
    'Saradomin cloak': `${WikiItemImages.BASE_URL}/Saradomin_cloak.png`,
    'Guthix mitre': `${WikiItemImages.BASE_URL}/Guthix_mitre.png`,
    'Guthix cloak': `${WikiItemImages.BASE_URL}/Guthix_cloak.png`,
    'Zamorak mitre': `${WikiItemImages.BASE_URL}/Zamorak_mitre.png`,
    'Zamorak cloak': `${WikiItemImages.BASE_URL}/Zamorak_cloak.png`,
    'Ancient mitre': `${WikiItemImages.BASE_URL}/Ancient_mitre.png`,
    'Ancient cloak': `${WikiItemImages.BASE_URL}/Ancient_cloak.png`,
    'Ancient stole': `${WikiItemImages.BASE_URL}/Ancient_stole.png`,
    'Ancient crozier': `${WikiItemImages.BASE_URL}/Ancient_crozier.png`,
    'Armadyl mitre': `${WikiItemImages.BASE_URL}/Armadyl_mitre.png`,
    'Armadyl cloak': `${WikiItemImages.BASE_URL}/Armadyl_cloak.png`,
    'Armadyl stole': `${WikiItemImages.BASE_URL}/Armadyl_stole.png`,
    'Armadyl crozier': `${WikiItemImages.BASE_URL}/Armadyl_crozier.png`,
    'Bandos mitre': `${WikiItemImages.BASE_URL}/Bandos_mitre.png`,
    'Bandos cloak': `${WikiItemImages.BASE_URL}/Bandos_cloak.png`,
    'Bandos stole': `${WikiItemImages.BASE_URL}/Bandos_stole.png`,
    'Bandos crozier': `${WikiItemImages.BASE_URL}/Bandos_crozier.png`,
    'Red boater': `${WikiItemImages.BASE_URL}/Red_boater.png`,
    'Green boater': `${WikiItemImages.BASE_URL}/Green_boater.png`,
    'Orange boater': `${WikiItemImages.BASE_URL}/Orange_boater.png`,
    'Black boater': `${WikiItemImages.BASE_URL}/Black_boater.png`,
    'Blue boater': `${WikiItemImages.BASE_URL}/Blue_boater.png`,
    'Pink boater': `${WikiItemImages.BASE_URL}/Pink_boater.png`,
    'Purple boater': `${WikiItemImages.BASE_URL}/Purple_boater.png`,
    'White boater': `${WikiItemImages.BASE_URL}/White_boater.png`,
    'Red headband': `${WikiItemImages.BASE_URL}/Red_headband.png`,
    'Black headband': `${WikiItemImages.BASE_URL}/Black_headband.png`,
    'Brown headband': `${WikiItemImages.BASE_URL}/Brown_headband.png`,
    'White headband': `${WikiItemImages.BASE_URL}/White_headband.png`,
    'Blue headband': `${WikiItemImages.BASE_URL}/Blue_headband.png`,
    'Gold headband': `${WikiItemImages.BASE_URL}/Gold_headband.png`,
    'Pink headband': `${WikiItemImages.BASE_URL}/Pink_headband.png`,
    'Green headband': `${WikiItemImages.BASE_URL}/Green_headband.png`,
    'Crier hat': `${WikiItemImages.BASE_URL}/Crier_hat.png`,
    'Crier coat': `${WikiItemImages.BASE_URL}/Crier_coat.png`,
    'Crier bell': `${WikiItemImages.BASE_URL}/Crier_bell.png`,
    'Adamant cane': `${WikiItemImages.BASE_URL}/Adamant_cane.png`,
    'Arceuus banner': `${WikiItemImages.BASE_URL}/Arceuus_banner.png`,
    'Piscarilius banner': `${WikiItemImages.BASE_URL}/Piscarilius_banner.png`,
    'Hosidius banner': `${WikiItemImages.BASE_URL}/Hosidius_banner.png`,
    'Shayzien banner': `${WikiItemImages.BASE_URL}/Shayzien_banner.png`,
    'Lovakengj banner': `${WikiItemImages.BASE_URL}/Lovakengj_banner.png`,
    'Cabbage round shield': `${WikiItemImages.BASE_URL}/Cabbage_round_shield.png`,
    'Cat mask': `${WikiItemImages.BASE_URL}/Cat_mask.png`,
    'Penguin mask': `${WikiItemImages.BASE_URL}/Penguin_mask.png`,
    'Leprechaun hat': `${WikiItemImages.BASE_URL}/Leprechaun_hat.png`,
    'Black leprechaun hat': `${WikiItemImages.BASE_URL}/Black_leprechaun_hat.png`,
    'Wolf mask': `${WikiItemImages.BASE_URL}/Wolf_mask.png`,
    'Wolf cloak': `${WikiItemImages.BASE_URL}/Wolf_cloak.png`,
    'Black unicorn mask': `${WikiItemImages.BASE_URL}/Black_unicorn_mask.png`,
    'White unicorn mask': `${WikiItemImages.BASE_URL}/White_unicorn_mask.png`,
    'Purple elegant shirt': `${WikiItemImages.BASE_URL}/Purple_elegant_shirt.png`,
    'Purple elegant blouse': `${WikiItemImages.BASE_URL}/Purple_elegant_blouse.png`,
    'Purple elegant legs': `${WikiItemImages.BASE_URL}/Purple_elegant_legs.png`,
    'Purple elegant skirt': `${WikiItemImages.BASE_URL}/Purple_elegant_skirt.png`,
    'Black elegant shirt': `${WikiItemImages.BASE_URL}/Black_elegant_shirt.png`,
    'White elegant blouse': `${WikiItemImages.BASE_URL}/White_elegant_blouse.png`,
    'Black elegant legs': `${WikiItemImages.BASE_URL}/Black_elegant_legs.png`,
    'White elegant skirt': `${WikiItemImages.BASE_URL}/White_elegant_skirt.png`,
    'Pink elegant shirt': `${WikiItemImages.BASE_URL}/Pink_elegant_shirt.png`,
    'Pink elegant blouse': `${WikiItemImages.BASE_URL}/Pink_elegant_blouse.png`,
    'Pink elegant legs': `${WikiItemImages.BASE_URL}/Pink_elegant_legs.png`,
    'Pink elegant skirt': `${WikiItemImages.BASE_URL}/Pink_elegant_skirt.png`,
    'Gold elegant shirt': `${WikiItemImages.BASE_URL}/Gold_elegant_shirt.png`,
    'Gold elegant blouse': `${WikiItemImages.BASE_URL}/Gold_elegant_blouse.png`,
    'Gold elegant legs': `${WikiItemImages.BASE_URL}/Gold_elegant_legs.png`,
    'Gold elegant skirt': `${WikiItemImages.BASE_URL}/Gold_elegant_skirt.png`,
    'Adamant full helm': `${WikiItemImages.BASE_URL}/Adamant_full_helm.png`,
    'Adamant platebody': `${WikiItemImages.BASE_URL}/Adamant_platebody.png`,
    'Adamant platelegs': `${WikiItemImages.BASE_URL}/Adamant_platelegs.png`,
    'Adamant longsword': `${WikiItemImages.BASE_URL}/Adamant_longsword.png`,
    'Adamant dagger': `${WikiItemImages.BASE_URL}/Adamant_dagger.png`,
    'Adamant battleaxe': `${WikiItemImages.BASE_URL}/Adamant_battleaxe.png`,
    'Adamant axe': `${WikiItemImages.BASE_URL}/Adamant_axe.png`,
    'Adamant pickaxe': `${WikiItemImages.BASE_URL}/Adamant_pickaxe.png`,
    'Green d\'hide body': `${WikiItemImages.BASE_URL}/Green_d'hide_body.png`,
    'Green d\'hide chaps': `${WikiItemImages.BASE_URL}/Green_d'hide_chaps.png`,
    'Yew shortbow': `${WikiItemImages.BASE_URL}/Yew_shortbow.png`,
    'Fire battlestaff': `${WikiItemImages.BASE_URL}/Fire_battlestaff.png`,
    'Yew longbow': `${WikiItemImages.BASE_URL}/Yew_longbow.png`,
    'Amulet of power': `${WikiItemImages.BASE_URL}/Amulet_of_power.png`,
    'Air rune': `${WikiItemImages.BASE_URL}/Air_rune.png`,
    'Mind rune': `${WikiItemImages.BASE_URL}/Mind_rune.png`,
    'Water rune': `${WikiItemImages.BASE_URL}/Water_rune.png`,
    'Earth rune': `${WikiItemImages.BASE_URL}/Earth_rune.png`,
    'Fire rune': `${WikiItemImages.BASE_URL}/Fire_rune.png`,
    'Chaos rune': `${WikiItemImages.BASE_URL}/Chaos_rune.png`,
    'Nature rune': `${WikiItemImages.BASE_URL}/Nature_rune.png`,
    'Law rune': `${WikiItemImages.BASE_URL}/Law_rune.png`,
    'Death rune': `${WikiItemImages.BASE_URL}/Death_rune.png`,
    'Lobster': `${WikiItemImages.BASE_URL}/Lobster.png`,
    'Swordfish': `${WikiItemImages.BASE_URL}/Swordfish.png`,
    'Coins (200-1000)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (5-10)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Coins (10k-15k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (8-12)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Red firelighter': `${WikiItemImages.BASE_URL}/Red_firelighter.png`,
    'Green firelighter': `${WikiItemImages.BASE_URL}/Green_firelighter.png`,
    'Blue firelighter': `${WikiItemImages.BASE_URL}/Blue_firelighter.png`,
    'Purple firelighter': `${WikiItemImages.BASE_URL}/Purple_firelighter.png`,
    'White firelighter': `${WikiItemImages.BASE_URL}/White_firelighter.png`,
    'Charge dragonstone jewellery scroll': `${WikiItemImages.BASE_URL}/Charge_dragonstone_jewellery_scroll.png`,
    'Nardah teleport': `${WikiItemImages.BASE_URL}/Nardah_teleport.png`,
    'Mos le\'harmless teleport': `${WikiItemImages.BASE_URL}/Mos_le'harmless_teleport.png`,
    'Mort\'ton teleport': `${WikiItemImages.BASE_URL}/Mort'ton_teleport.png`,
    'Feldip hills teleport': `${WikiItemImages.BASE_URL}/Feldip_hills_teleport.png`,
    'Lunar isle teleport': `${WikiItemImages.BASE_URL}/Lunar_isle_teleport.png`,
    'Digsite teleport': `${WikiItemImages.BASE_URL}/Digsite_teleport.png`,
    'Piscatoris teleport': `${WikiItemImages.BASE_URL}/Piscatoris_teleport.png`,
    'Pest control teleport': `${WikiItemImages.BASE_URL}/Pest_control_teleport.png`,
    'Tai bwo wannai teleport': `${WikiItemImages.BASE_URL}/Tai_bwo_wannai_teleport.png`,
    'Lumberyard teleport': `${WikiItemImages.BASE_URL}/Lumberyard_teleport.png`,
    'Iorwerth camp teleport': `${WikiItemImages.BASE_URL}/Iorwerth_camp_teleport.png`,
    'Holy blessing': `${WikiItemImages.BASE_URL}/Holy_blessing.png`,
    'Unholy blessing': `${WikiItemImages.BASE_URL}/Unholy_blessing.png`,
    'Peaceful blessing': `${WikiItemImages.BASE_URL}/Peaceful_blessing.png`,
    'War blessing': `${WikiItemImages.BASE_URL}/War_blessing.png`,
    'Honourable blessing': `${WikiItemImages.BASE_URL}/Honourable_blessing.png`,
    'Ancient blessing': `${WikiItemImages.BASE_URL}/Ancient_blessing.png`,
    'Master scroll book (empty)': `${WikiItemImages.BASE_URL}/Master_scroll_book_(empty).png`,
    'Saradomin page 1': `${WikiItemImages.BASE_URL}/Saradomin_page_1.png`,
    'Saradomin page 2': `${WikiItemImages.BASE_URL}/Saradomin_page_2.png`,
    'Saradomin page 3': `${WikiItemImages.BASE_URL}/Saradomin_page_3.png`,
    'Saradomin page 4': `${WikiItemImages.BASE_URL}/Saradomin_page_4.png`,
    'Zamorak page 1': `${WikiItemImages.BASE_URL}/Zamorak_page_1.png`,
    'Zamorak page 2': `${WikiItemImages.BASE_URL}/Zamorak_page_2.png`,
    'Zamorak page 3': `${WikiItemImages.BASE_URL}/Zamorak_page_3.png`,
    'Zamorak page 4': `${WikiItemImages.BASE_URL}/Zamorak_page_4.png`,
    'Guthix page 1': `${WikiItemImages.BASE_URL}/Guthix_page_1.png`,
    'Guthix page 2': `${WikiItemImages.BASE_URL}/Guthix_page_2.png`,
    'Guthix page 3': `${WikiItemImages.BASE_URL}/Guthix_page_3.png`,
    'Guthix page 4': `${WikiItemImages.BASE_URL}/Guthix_page_4.png`,
    'Bandos page 1': `${WikiItemImages.BASE_URL}/Bandos_page_1.png`,
    'Bandos page 2': `${WikiItemImages.BASE_URL}/Bandos_page_2.png`,
    'Bandos page 3': `${WikiItemImages.BASE_URL}/Bandos_page_3.png`,
    'Bandos page 4': `${WikiItemImages.BASE_URL}/Bandos_page_4.png`,
    'Armadyl page 1': `${WikiItemImages.BASE_URL}/Armadyl_page_1.png`,
    'Armadyl page 2': `${WikiItemImages.BASE_URL}/Armadyl_page_2.png`,
    'Armadyl page 3': `${WikiItemImages.BASE_URL}/Armadyl_page_3.png`,
    'Armadyl page 4': `${WikiItemImages.BASE_URL}/Armadyl_page_4.png`,
    'Ancient page 1': `${WikiItemImages.BASE_URL}/Ancient_page_1.png`,
    'Ancient page 2': `${WikiItemImages.BASE_URL}/Ancient_page_2.png`,
    'Ancient page 3': `${WikiItemImages.BASE_URL}/Ancient_page_3.png`,
    'Ancient page 4': `${WikiItemImages.BASE_URL}/Ancient_page_4.png`,
    'Clue scroll (master)': `${WikiItemImages.BASE_URL}/Clue_scroll_(master).png`,
  };

  /** Hard clue scroll rewards (230 items). */
  static readonly HARD: Record<string, string> = {
    'Magic comp bow': `${WikiItemImages.BASE_URL}/Magic_comp_bow.png`,
    'Amulet of glory (t4)': `${WikiItemImages.BASE_URL}/Amulet_of_glory_(t4).png`,
    'Robin hood hat': `${WikiItemImages.BASE_URL}/Robin_hood_hat.png`,
    'Enchanted hat': `${WikiItemImages.BASE_URL}/Enchanted_hat.png`,
    'Enchanted top': `${WikiItemImages.BASE_URL}/Enchanted_top.png`,
    'Enchanted robe': `${WikiItemImages.BASE_URL}/Enchanted_robe.png`,
    'Dragon boots ornament kit': `${WikiItemImages.BASE_URL}/Dragon_boots_ornament_kit.png`,
    'Rune full helm (t)': `${WikiItemImages.BASE_URL}/Rune_full_helm_(t).png`,
    'Rune platebody (t)': `${WikiItemImages.BASE_URL}/Rune_platebody_(t).png`,
    'Rune platelegs (t)': `${WikiItemImages.BASE_URL}/Rune_platelegs_(t).png`,
    'Rune plateskirt (t)': `${WikiItemImages.BASE_URL}/Rune_plateskirt_(t).png`,
    'Rune kiteshield (t)': `${WikiItemImages.BASE_URL}/Rune_kiteshield_(t).png`,
    'Rune full helm (g)': `${WikiItemImages.BASE_URL}/Rune_full_helm_(g).png`,
    'Rune platebody (g)': `${WikiItemImages.BASE_URL}/Rune_platebody_(g).png`,
    'Rune platelegs (g)': `${WikiItemImages.BASE_URL}/Rune_platelegs_(g).png`,
    'Rune plateskirt (g)': `${WikiItemImages.BASE_URL}/Rune_plateskirt_(g).png`,
    'Rune kiteshield (g)': `${WikiItemImages.BASE_URL}/Rune_kiteshield_(g).png`,
    'Rune shield (h1)': `${WikiItemImages.BASE_URL}/Rune_shield_(h1).png`,
    'Rune shield (h2)': `${WikiItemImages.BASE_URL}/Rune_shield_(h2).png`,
    'Rune shield (h3)': `${WikiItemImages.BASE_URL}/Rune_shield_(h3).png`,
    'Rune shield (h4)': `${WikiItemImages.BASE_URL}/Rune_shield_(h4).png`,
    'Rune shield (h5)': `${WikiItemImages.BASE_URL}/Rune_shield_(h5).png`,
    'Rune helm (h1)': `${WikiItemImages.BASE_URL}/Rune_helm_(h1).png`,
    'Rune helm (h2)': `${WikiItemImages.BASE_URL}/Rune_helm_(h2).png`,
    'Rune helm (h3)': `${WikiItemImages.BASE_URL}/Rune_helm_(h3).png`,
    'Rune helm (h4)': `${WikiItemImages.BASE_URL}/Rune_helm_(h4).png`,
    'Rune helm (h5)': `${WikiItemImages.BASE_URL}/Rune_helm_(h5).png`,
    'Saradomin full helm': `${WikiItemImages.BASE_URL}/Saradomin_full_helm.png`,
    'Saradomin platebody': `${WikiItemImages.BASE_URL}/Saradomin_platebody.png`,
    'Saradomin platelegs': `${WikiItemImages.BASE_URL}/Saradomin_platelegs.png`,
    'Saradomin kiteshield': `${WikiItemImages.BASE_URL}/Saradomin_kiteshield.png`,
    'Zamorak full helm': `${WikiItemImages.BASE_URL}/Zamorak_full_helm.png`,
    'Zamorak platebody': `${WikiItemImages.BASE_URL}/Zamorak_platebody.png`,
    'Zamorak platelegs': `${WikiItemImages.BASE_URL}/Zamorak_platelegs.png`,
    'Zamorak kiteshield': `${WikiItemImages.BASE_URL}/Zamorak_kiteshield.png`,
    'Guthix full helm': `${WikiItemImages.BASE_URL}/Guthix_full_helm.png`,
    'Guthix platebody': `${WikiItemImages.BASE_URL}/Guthix_platebody.png`,
    'Guthix platelegs': `${WikiItemImages.BASE_URL}/Guthix_platelegs.png`,
    'Guthix kiteshield': `${WikiItemImages.BASE_URL}/Guthix_kiteshield.png`,
    'Ancient full helm': `${WikiItemImages.BASE_URL}/Ancient_full_helm.png`,
    'Ancient platebody': `${WikiItemImages.BASE_URL}/Ancient_platebody.png`,
    'Ancient platelegs': `${WikiItemImages.BASE_URL}/Ancient_platelegs.png`,
    'Ancient kiteshield': `${WikiItemImages.BASE_URL}/Ancient_kiteshield.png`,
    'Armadyl full helm': `${WikiItemImages.BASE_URL}/Armadyl_full_helm.png`,
    'Armadyl platebody': `${WikiItemImages.BASE_URL}/Armadyl_platebody.png`,
    'Armadyl platelegs': `${WikiItemImages.BASE_URL}/Armadyl_platelegs.png`,
    'Armadyl kiteshield': `${WikiItemImages.BASE_URL}/Armadyl_kiteshield.png`,
    'Bandos full helm': `${WikiItemImages.BASE_URL}/Bandos_full_helm.png`,
    'Bandos platebody': `${WikiItemImages.BASE_URL}/Bandos_platebody.png`,
    'Bandos platelegs': `${WikiItemImages.BASE_URL}/Bandos_platelegs.png`,
    'Bandos kiteshield': `${WikiItemImages.BASE_URL}/Bandos_kiteshield.png`,
    'Red d\'hide body (g)': `${WikiItemImages.BASE_URL}/Red_d'hide_body_(g).png`,
    'Red d\'hide body (t)': `${WikiItemImages.BASE_URL}/Red_d'hide_body_(t).png`,
    'Red d\'hide chaps (g)': `${WikiItemImages.BASE_URL}/Red_d'hide_chaps_(g).png`,
    'Red d\'hide chaps (t)': `${WikiItemImages.BASE_URL}/Red_d'hide_chaps_(t).png`,
    'Blue d\'hide body (g)': `${WikiItemImages.BASE_URL}/Blue_d'hide_body_(g).png`,
    'Blue d\'hide body (t)': `${WikiItemImages.BASE_URL}/Blue_d'hide_body_(t).png`,
    'Blue d\'hide chaps (g)': `${WikiItemImages.BASE_URL}/Blue_d'hide_chaps_(g).png`,
    'Blue d\'hide chaps (t)': `${WikiItemImages.BASE_URL}/Blue_d'hide_chaps_(t).png`,
    'Saradomin coif': `${WikiItemImages.BASE_URL}/Saradomin_coif.png`,
    'Saradomin d\'hide body': `${WikiItemImages.BASE_URL}/Saradomin_d'hide_body.png`,
    'Saradomin chaps': `${WikiItemImages.BASE_URL}/Saradomin_chaps.png`,
    'Saradomin bracers': `${WikiItemImages.BASE_URL}/Saradomin_bracers.png`,
    'Saradomin d\'hide boots': `${WikiItemImages.BASE_URL}/Saradomin_d'hide_boots.png`,
    'Guthix coif': `${WikiItemImages.BASE_URL}/Guthix_coif.png`,
    'Guthix d\'hide body': `${WikiItemImages.BASE_URL}/Guthix_d'hide_body.png`,
    'Guthix chaps': `${WikiItemImages.BASE_URL}/Guthix_chaps.png`,
    'Guthix bracers': `${WikiItemImages.BASE_URL}/Guthix_bracers.png`,
    'Guthix d\'hide boots': `${WikiItemImages.BASE_URL}/Guthix_d'hide_boots.png`,
    'Zamorak coif': `${WikiItemImages.BASE_URL}/Zamorak_coif.png`,
    'Zamorak d\'hide body': `${WikiItemImages.BASE_URL}/Zamorak_d'hide_body.png`,
    'Zamorak chaps': `${WikiItemImages.BASE_URL}/Zamorak_chaps.png`,
    'Zamorak bracers': `${WikiItemImages.BASE_URL}/Zamorak_bracers.png`,
    'Zamorak d\'hide boots': `${WikiItemImages.BASE_URL}/Zamorak_d'hide_boots.png`,
    'Bandos coif': `${WikiItemImages.BASE_URL}/Bandos_coif.png`,
    'Bandos d\'hide body': `${WikiItemImages.BASE_URL}/Bandos_d'hide_body.png`,
    'Bandos chaps': `${WikiItemImages.BASE_URL}/Bandos_chaps.png`,
    'Bandos bracers': `${WikiItemImages.BASE_URL}/Bandos_bracers.png`,
    'Bandos d\'hide boots': `${WikiItemImages.BASE_URL}/Bandos_d'hide_boots.png`,
    'Armadyl coif': `${WikiItemImages.BASE_URL}/Armadyl_coif.png`,
    'Armadyl d\'hide body': `${WikiItemImages.BASE_URL}/Armadyl_d'hide_body.png`,
    'Armadyl chaps': `${WikiItemImages.BASE_URL}/Armadyl_chaps.png`,
    'Armadyl bracers': `${WikiItemImages.BASE_URL}/Armadyl_bracers.png`,
    'Armadyl d\'hide boots': `${WikiItemImages.BASE_URL}/Armadyl_d'hide_boots.png`,
    'Saradomin stole': `${WikiItemImages.BASE_URL}/Saradomin_stole.png`,
    'Saradomin crozier': `${WikiItemImages.BASE_URL}/Saradomin_crozier.png`,
    'Guthix stole': `${WikiItemImages.BASE_URL}/Guthix_stole.png`,
    'Guthix crozier': `${WikiItemImages.BASE_URL}/Guthix_crozier.png`,
    'Zamorak stole': `${WikiItemImages.BASE_URL}/Zamorak_stole.png`,
    'Zamorak crozier': `${WikiItemImages.BASE_URL}/Zamorak_crozier.png`,
    'Ancient coif': `${WikiItemImages.BASE_URL}/Ancient_coif.png`,
    'Ancient d\'hide body': `${WikiItemImages.BASE_URL}/Ancient_d'hide_body.png`,
    'Ancient chaps': `${WikiItemImages.BASE_URL}/Ancient_chaps.png`,
    'Ancient bracers': `${WikiItemImages.BASE_URL}/Ancient_bracers.png`,
    'Ancient d\'hide boots': `${WikiItemImages.BASE_URL}/Ancient_d'hide_boots.png`,
    'Zombie head (Treasure Trails)': `${WikiItemImages.BASE_URL}/Zombie_head_(Treasure_Trails).png`,
    'Cyclops head': `${WikiItemImages.BASE_URL}/Cyclops_head.png`,
    'Pirate\'s hat': `${WikiItemImages.BASE_URL}/Pirate's_hat.png`,
    'Red cavalier': `${WikiItemImages.BASE_URL}/Red_cavalier.png`,
    'White cavalier': `${WikiItemImages.BASE_URL}/White_cavalier.png`,
    'Navy cavalier': `${WikiItemImages.BASE_URL}/Navy_cavalier.png`,
    'Tan cavalier': `${WikiItemImages.BASE_URL}/Tan_cavalier.png`,
    'Dark cavalier': `${WikiItemImages.BASE_URL}/Dark_cavalier.png`,
    'Black cavalier': `${WikiItemImages.BASE_URL}/Black_cavalier.png`,
    'Pith helmet': `${WikiItemImages.BASE_URL}/Pith_helmet.png`,
    'Explorer backpack': `${WikiItemImages.BASE_URL}/Explorer_backpack.png`,
    'Green dragon mask': `${WikiItemImages.BASE_URL}/Green_dragon_mask.png`,
    'Blue dragon mask': `${WikiItemImages.BASE_URL}/Blue_dragon_mask.png`,
    'Red dragon mask': `${WikiItemImages.BASE_URL}/Red_dragon_mask.png`,
    'Black dragon mask': `${WikiItemImages.BASE_URL}/Black_dragon_mask.png`,
    'Nunchaku': `${WikiItemImages.BASE_URL}/Nunchaku.png`,
    'Rune cane': `${WikiItemImages.BASE_URL}/Rune_cane.png`,
    'Dual sai': `${WikiItemImages.BASE_URL}/Dual_sai.png`,
    'Thieving bag': `${WikiItemImages.BASE_URL}/Thieving_bag.png`,
    'Rune defender ornament kit': `${WikiItemImages.BASE_URL}/Rune_defender_ornament_kit.png`,
    'Berserker necklace ornament kit': `${WikiItemImages.BASE_URL}/Berserker_necklace_ornament_kit.png`,
    'Tzhaar-ket-om ornament kit': `${WikiItemImages.BASE_URL}/Tzhaar-ket-om_ornament_kit.png`,
    'Rune platebody (h1)': `${WikiItemImages.BASE_URL}/Rune_platebody_(h1).png`,
    'Rune platebody (h2)': `${WikiItemImages.BASE_URL}/Rune_platebody_(h2).png`,
    'Rune platebody (h3)': `${WikiItemImages.BASE_URL}/Rune_platebody_(h3).png`,
    'Rune platebody (h4)': `${WikiItemImages.BASE_URL}/Rune_platebody_(h4).png`,
    'Rune platebody (h5)': `${WikiItemImages.BASE_URL}/Rune_platebody_(h5).png`,
    'Saradomin d\'hide shield': `${WikiItemImages.BASE_URL}/Saradomin_d'hide_shield.png`,
    'Guthix d\'hide shield': `${WikiItemImages.BASE_URL}/Guthix_d'hide_shield.png`,
    'Zamorak d\'hide shield': `${WikiItemImages.BASE_URL}/Zamorak_d'hide_shield.png`,
    'Bandos d\'hide shield': `${WikiItemImages.BASE_URL}/Bandos_d'hide_shield.png`,
    'Armadyl d\'hide shield': `${WikiItemImages.BASE_URL}/Armadyl_d'hide_shield.png`,
    'Ancient d\'hide shield': `${WikiItemImages.BASE_URL}/Ancient_d'hide_shield.png`,
    'Rune full helm': `${WikiItemImages.BASE_URL}/Rune_full_helm.png`,
    'Rune platebody': `${WikiItemImages.BASE_URL}/Rune_platebody.png`,
    'Rune platelegs': `${WikiItemImages.BASE_URL}/Rune_platelegs.png`,
    'Rune plateskirt': `${WikiItemImages.BASE_URL}/Rune_plateskirt.png`,
    'Rune kiteshield': `${WikiItemImages.BASE_URL}/Rune_kiteshield.png`,
    'Rune longsword': `${WikiItemImages.BASE_URL}/Rune_longsword.png`,
    'Rune dagger': `${WikiItemImages.BASE_URL}/Rune_dagger.png`,
    'Rune battleaxe': `${WikiItemImages.BASE_URL}/Rune_battleaxe.png`,
    'Rune axe': `${WikiItemImages.BASE_URL}/Rune_axe.png`,
    'Rune pickaxe': `${WikiItemImages.BASE_URL}/Rune_pickaxe.png`,
    'Black d\'hide body': `${WikiItemImages.BASE_URL}/Black_d'hide_body.png`,
    'Black d\'hide chaps': `${WikiItemImages.BASE_URL}/Black_d'hide_chaps.png`,
    'Magic shortbow': `${WikiItemImages.BASE_URL}/Magic_shortbow.png`,
    'Magic longbow': `${WikiItemImages.BASE_URL}/Magic_longbow.png`,
    'Nature rune': `${WikiItemImages.BASE_URL}/Nature_rune.png`,
    'Law rune': `${WikiItemImages.BASE_URL}/Law_rune.png`,
    'Blood rune': `${WikiItemImages.BASE_URL}/Blood_rune.png`,
    'Lobster': `${WikiItemImages.BASE_URL}/Lobster.png`,
    'Shark': `${WikiItemImages.BASE_URL}/Shark.png`,
    'Super energy(4)': `${WikiItemImages.BASE_URL}/Super_energy(4).png`,
    'Super restore(4)': `${WikiItemImages.BASE_URL}/Super_restore(4).png`,
    'Antifire potion(4)': `${WikiItemImages.BASE_URL}/Antifire_potion(4).png`,
    'Super attack(4)': `${WikiItemImages.BASE_URL}/Super_attack(4).png`,
    'Super strength(4)': `${WikiItemImages.BASE_URL}/Super_strength(4).png`,
    'Super defence(4)': `${WikiItemImages.BASE_URL}/Super_defence(4).png`,
    'Gilded full helm': `${WikiItemImages.BASE_URL}/Gilded_full_helm.png`,
    'Gilded platebody': `${WikiItemImages.BASE_URL}/Gilded_platebody.png`,
    'Gilded platelegs': `${WikiItemImages.BASE_URL}/Gilded_platelegs.png`,
    'Gilded plateskirt': `${WikiItemImages.BASE_URL}/Gilded_plateskirt.png`,
    'Gilded kiteshield': `${WikiItemImages.BASE_URL}/Gilded_kiteshield.png`,
    'Gilded med helm': `${WikiItemImages.BASE_URL}/Gilded_med_helm.png`,
    'Gilded chainbody': `${WikiItemImages.BASE_URL}/Gilded_chainbody.png`,
    'Gilded sq shield': `${WikiItemImages.BASE_URL}/Gilded_sq_shield.png`,
    'Gilded 2h sword': `${WikiItemImages.BASE_URL}/Gilded_2h_sword.png`,
    'Gilded spear': `${WikiItemImages.BASE_URL}/Gilded_spear.png`,
    'Gilded hasta': `${WikiItemImages.BASE_URL}/Gilded_hasta.png`,
    '3rd age full helmet': `${WikiItemImages.BASE_URL}/3rd_age_full_helmet.png`,
    '3rd age platebody': `${WikiItemImages.BASE_URL}/3rd_age_platebody.png`,
    '3rd age platelegs': `${WikiItemImages.BASE_URL}/3rd_age_platelegs.png`,
    '3rd age plateskirt': `${WikiItemImages.BASE_URL}/3rd_age_plateskirt.png`,
    '3rd age kiteshield': `${WikiItemImages.BASE_URL}/3rd_age_kiteshield.png`,
    '3rd age range coif': `${WikiItemImages.BASE_URL}/3rd_age_range_coif.png`,
    '3rd age range top': `${WikiItemImages.BASE_URL}/3rd_age_range_top.png`,
    '3rd age range legs': `${WikiItemImages.BASE_URL}/3rd_age_range_legs.png`,
    '3rd age vambraces': `${WikiItemImages.BASE_URL}/3rd_age_vambraces.png`,
    '3rd age mage hat': `${WikiItemImages.BASE_URL}/3rd_age_mage_hat.png`,
    '3rd age robe top': `${WikiItemImages.BASE_URL}/3rd_age_robe_top.png`,
    '3rd age robe': `${WikiItemImages.BASE_URL}/3rd_age_robe.png`,
    '3rd age amulet': `${WikiItemImages.BASE_URL}/3rd_age_amulet.png`,
    'Coins (1k-5k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (7-15)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Coins (10k-15k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (8-12)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Red firelighter': `${WikiItemImages.BASE_URL}/Red_firelighter.png`,
    'Green firelighter': `${WikiItemImages.BASE_URL}/Green_firelighter.png`,
    'Blue firelighter': `${WikiItemImages.BASE_URL}/Blue_firelighter.png`,
    'Purple firelighter': `${WikiItemImages.BASE_URL}/Purple_firelighter.png`,
    'White firelighter': `${WikiItemImages.BASE_URL}/White_firelighter.png`,
    'Charge dragonstone jewellery scroll': `${WikiItemImages.BASE_URL}/Charge_dragonstone_jewellery_scroll.png`,
    'Nardah teleport': `${WikiItemImages.BASE_URL}/Nardah_teleport.png`,
    'Mos le\'harmless teleport': `${WikiItemImages.BASE_URL}/Mos_le'harmless_teleport.png`,
    'Mort\'ton teleport': `${WikiItemImages.BASE_URL}/Mort'ton_teleport.png`,
    'Feldip hills teleport': `${WikiItemImages.BASE_URL}/Feldip_hills_teleport.png`,
    'Lunar isle teleport': `${WikiItemImages.BASE_URL}/Lunar_isle_teleport.png`,
    'Digsite teleport': `${WikiItemImages.BASE_URL}/Digsite_teleport.png`,
    'Piscatoris teleport': `${WikiItemImages.BASE_URL}/Piscatoris_teleport.png`,
    'Pest control teleport': `${WikiItemImages.BASE_URL}/Pest_control_teleport.png`,
    'Tai bwo wannai teleport': `${WikiItemImages.BASE_URL}/Tai_bwo_wannai_teleport.png`,
    'Lumberyard teleport': `${WikiItemImages.BASE_URL}/Lumberyard_teleport.png`,
    'Iorwerth camp teleport': `${WikiItemImages.BASE_URL}/Iorwerth_camp_teleport.png`,
    'Holy blessing': `${WikiItemImages.BASE_URL}/Holy_blessing.png`,
    'Unholy blessing': `${WikiItemImages.BASE_URL}/Unholy_blessing.png`,
    'Peaceful blessing': `${WikiItemImages.BASE_URL}/Peaceful_blessing.png`,
    'War blessing': `${WikiItemImages.BASE_URL}/War_blessing.png`,
    'Honourable blessing': `${WikiItemImages.BASE_URL}/Honourable_blessing.png`,
    'Ancient blessing': `${WikiItemImages.BASE_URL}/Ancient_blessing.png`,
    'Master scroll book (empty)': `${WikiItemImages.BASE_URL}/Master_scroll_book_(empty).png`,
    'Saradomin page 1': `${WikiItemImages.BASE_URL}/Saradomin_page_1.png`,
    'Saradomin page 2': `${WikiItemImages.BASE_URL}/Saradomin_page_2.png`,
    'Saradomin page 3': `${WikiItemImages.BASE_URL}/Saradomin_page_3.png`,
    'Saradomin page 4': `${WikiItemImages.BASE_URL}/Saradomin_page_4.png`,
    'Zamorak page 1': `${WikiItemImages.BASE_URL}/Zamorak_page_1.png`,
    'Zamorak page 2': `${WikiItemImages.BASE_URL}/Zamorak_page_2.png`,
    'Zamorak page 3': `${WikiItemImages.BASE_URL}/Zamorak_page_3.png`,
    'Zamorak page 4': `${WikiItemImages.BASE_URL}/Zamorak_page_4.png`,
    'Guthix page 1': `${WikiItemImages.BASE_URL}/Guthix_page_1.png`,
    'Guthix page 2': `${WikiItemImages.BASE_URL}/Guthix_page_2.png`,
    'Guthix page 3': `${WikiItemImages.BASE_URL}/Guthix_page_3.png`,
    'Guthix page 4': `${WikiItemImages.BASE_URL}/Guthix_page_4.png`,
    'Bandos page 1': `${WikiItemImages.BASE_URL}/Bandos_page_1.png`,
    'Bandos page 2': `${WikiItemImages.BASE_URL}/Bandos_page_2.png`,
    'Bandos page 3': `${WikiItemImages.BASE_URL}/Bandos_page_3.png`,
    'Bandos page 4': `${WikiItemImages.BASE_URL}/Bandos_page_4.png`,
    'Armadyl page 1': `${WikiItemImages.BASE_URL}/Armadyl_page_1.png`,
    'Armadyl page 2': `${WikiItemImages.BASE_URL}/Armadyl_page_2.png`,
    'Armadyl page 3': `${WikiItemImages.BASE_URL}/Armadyl_page_3.png`,
    'Armadyl page 4': `${WikiItemImages.BASE_URL}/Armadyl_page_4.png`,
    'Ancient page 1': `${WikiItemImages.BASE_URL}/Ancient_page_1.png`,
    'Ancient page 2': `${WikiItemImages.BASE_URL}/Ancient_page_2.png`,
    'Ancient page 3': `${WikiItemImages.BASE_URL}/Ancient_page_3.png`,
    'Ancient page 4': `${WikiItemImages.BASE_URL}/Ancient_page_4.png`,
    'Clue scroll (master)': `${WikiItemImages.BASE_URL}/Clue_scroll_(master).png`,
  };

  /** Elite clue scroll rewards (183 items). */
  static readonly ELITE: Record<string, string> = {
    'Dragon full helm ornament kit': `${WikiItemImages.BASE_URL}/Dragon_full_helm_ornament_kit.png`,
    'Dragon chainbody ornament kit': `${WikiItemImages.BASE_URL}/Dragon_chainbody_ornament_kit.png`,
    'Dragon legs/skirt ornament kit': `${WikiItemImages.BASE_URL}/Dragon_legs+skirt_ornament_kit.png`,
    'Dragon sq shield ornament kit': `${WikiItemImages.BASE_URL}/Dragon_sq_shield_ornament_kit.png`,
    'Dragon scimitar ornament kit': `${WikiItemImages.BASE_URL}/Dragon_scimitar_ornament_kit.png`,
    'Fury ornament kit': `${WikiItemImages.BASE_URL}/Fury_ornament_kit.png`,
    'Light infinity colour kit': `${WikiItemImages.BASE_URL}/Light_infinity_colour_kit.png`,
    'Dark infinity colour kit': `${WikiItemImages.BASE_URL}/Dark_infinity_colour_kit.png`,
    'Royal crown': `${WikiItemImages.BASE_URL}/Royal_crown.png`,
    'Royal gown top': `${WikiItemImages.BASE_URL}/Royal_gown_top.png`,
    'Royal gown bottom': `${WikiItemImages.BASE_URL}/Royal_gown_bottom.png`,
    'Royal sceptre': `${WikiItemImages.BASE_URL}/Royal_sceptre.png`,
    'Musketeer hat': `${WikiItemImages.BASE_URL}/Musketeer_hat.png`,
    'Musketeer tabard': `${WikiItemImages.BASE_URL}/Musketeer_tabard.png`,
    'Musketeer pants': `${WikiItemImages.BASE_URL}/Musketeer_pants.png`,
    'Black d\'hide body (g)': `${WikiItemImages.BASE_URL}/Black_d'hide_body_(g).png`,
    'Black d\'hide body (t)': `${WikiItemImages.BASE_URL}/Black_d'hide_body_(t).png`,
    'Black d\'hide chaps (g)': `${WikiItemImages.BASE_URL}/Black_d'hide_chaps_(g).png`,
    'Black d\'hide chaps (t)': `${WikiItemImages.BASE_URL}/Black_d'hide_chaps_(t).png`,
    'Ranger\'s tunic': `${WikiItemImages.BASE_URL}/Rangers'_tunic.png`,
    'Ranger gloves': `${WikiItemImages.BASE_URL}/Ranger_gloves.png`,
    'Holy wraps': `${WikiItemImages.BASE_URL}/Holy_wraps.png`,
    'Bronze dragon mask': `${WikiItemImages.BASE_URL}/Bronze_dragon_mask.png`,
    'Iron dragon mask': `${WikiItemImages.BASE_URL}/Iron_dragon_mask.png`,
    'Steel dragon mask': `${WikiItemImages.BASE_URL}/Steel_dragon_mask.png`,
    'Mithril dragon mask': `${WikiItemImages.BASE_URL}/Mithril_dragon_mask.png`,
    'Adamant dragon mask': `${WikiItemImages.BASE_URL}/Adamant_dragon_mask.png`,
    'Rune dragon mask': `${WikiItemImages.BASE_URL}/Rune_dragon_mask.png`,
    'Arceuus scarf': `${WikiItemImages.BASE_URL}/Arceuus_scarf.png`,
    'Hosidius scarf': `${WikiItemImages.BASE_URL}/Hosidius_scarf.png`,
    'Lovakengj scarf': `${WikiItemImages.BASE_URL}/Lovakengj_scarf.png`,
    'Piscarilius scarf': `${WikiItemImages.BASE_URL}/Piscarilius_scarf.png`,
    'Shayzien scarf': `${WikiItemImages.BASE_URL}/Shayzien_scarf.png`,
    'Katana': `${WikiItemImages.BASE_URL}/Katana.png`,
    'Dragon cane': `${WikiItemImages.BASE_URL}/Dragon_cane.png`,
    'Bucket helm': `${WikiItemImages.BASE_URL}/Bucket_helm.png`,
    'Blacksmith\'s helm': `${WikiItemImages.BASE_URL}/Blacksmith's_helm.png`,
    'Deerstalker': `${WikiItemImages.BASE_URL}/Deerstalker.png`,
    'Afro': `${WikiItemImages.BASE_URL}/Afro.png`,
    'Big pirate hat': `${WikiItemImages.BASE_URL}/Big_pirate_hat.png`,
    'Top hat': `${WikiItemImages.BASE_URL}/Top_hat.png`,
    'Monocle': `${WikiItemImages.BASE_URL}/Monocle.png`,
    'Briefcase': `${WikiItemImages.BASE_URL}/Briefcase.png`,
    'Sagacious spectacles': `${WikiItemImages.BASE_URL}/Sagacious_spectacles.png`,
    'Ranger\'s tights': `${WikiItemImages.BASE_URL}/Rangers'_tights.png`,
    'Uri\'s hat': `${WikiItemImages.BASE_URL}/Uri's_hat.png`,
    'Giant boot': `${WikiItemImages.BASE_URL}/Giant_boot.png`,
    'Fremennik kilt': `${WikiItemImages.BASE_URL}/Fremennik_kilt.png`,
    'Dark bow tie': `${WikiItemImages.BASE_URL}/Dark_bow_tie.png`,
    'Dark tuxedo jacket': `${WikiItemImages.BASE_URL}/Dark_tuxedo_jacket.png`,
    'Dark tuxedo cuffs': `${WikiItemImages.BASE_URL}/Dark_tuxedo_cuffs.png`,
    'Dark trousers': `${WikiItemImages.BASE_URL}/Dark_trousers.png`,
    'Dark tuxedo shoes': `${WikiItemImages.BASE_URL}/Dark_tuxedo_shoes.png`,
    'Light bow tie': `${WikiItemImages.BASE_URL}/Light_bow_tie.png`,
    'Light tuxedo jacket': `${WikiItemImages.BASE_URL}/Light_tuxedo_jacket.png`,
    'Light tuxedo cuffs': `${WikiItemImages.BASE_URL}/Light_tuxedo_cuffs.png`,
    'Light trousers': `${WikiItemImages.BASE_URL}/Light_trousers.png`,
    'Light tuxedo shoes': `${WikiItemImages.BASE_URL}/Light_tuxedo_shoes.png`,
    'Rune platebody': `${WikiItemImages.BASE_URL}/Rune_platebody.png`,
    'Rune platelegs': `${WikiItemImages.BASE_URL}/Rune_platelegs.png`,
    'Rune plateskirt': `${WikiItemImages.BASE_URL}/Rune_plateskirt.png`,
    'Rune kiteshield': `${WikiItemImages.BASE_URL}/Rune_kiteshield.png`,
    'Rune crossbow': `${WikiItemImages.BASE_URL}/Rune_crossbow.png`,
    'Dragon dagger': `${WikiItemImages.BASE_URL}/Dragon_dagger.png`,
    'Dragon mace': `${WikiItemImages.BASE_URL}/Dragon_mace.png`,
    'Dragon longsword': `${WikiItemImages.BASE_URL}/Dragon_longsword.png`,
    'Onyx bolt tips': `${WikiItemImages.BASE_URL}/Onyx_bolt_tips_detail.png`,
    'Law rune': `${WikiItemImages.BASE_URL}/Law_rune.png`,
    'Death rune': `${WikiItemImages.BASE_URL}/Death_rune.png`,
    'Blood rune': `${WikiItemImages.BASE_URL}/Blood_rune.png`,
    'Soul rune': `${WikiItemImages.BASE_URL}/Soul_rune.png`,
    'Dragonstone bracelet': `${WikiItemImages.BASE_URL}/Dragonstone_bracelet.png`,
    'Dragon necklace': `${WikiItemImages.BASE_URL}/Dragon_necklace.png`,
    'Dragonstone ring': `${WikiItemImages.BASE_URL}/Dragonstone_ring.png`,
    'Tuna potato': `${WikiItemImages.BASE_URL}/Tuna_potato.png`,
    'Summer pie': `${WikiItemImages.BASE_URL}/Summer_pie.png`,
    'Oak plank': `${WikiItemImages.BASE_URL}/Oak_plank.png`,
    'Teak plank': `${WikiItemImages.BASE_URL}/Teak_plank.png`,
    'Mahogany plank': `${WikiItemImages.BASE_URL}/Mahogany_plank.png`,
    'Runite bar': `${WikiItemImages.BASE_URL}/Runite_bar.png`,
    'Tooth half of key': `${WikiItemImages.BASE_URL}/Tooth_half_of_key.png`,
    'Loop half of key': `${WikiItemImages.BASE_URL}/Loop_half_of_key.png`,
    'Palm tree seed': `${WikiItemImages.BASE_URL}/Palm_tree_seed_detail.png`,
    'Yew seed': `${WikiItemImages.BASE_URL}/Yew_seed_detail.png`,
    'Magic seed': `${WikiItemImages.BASE_URL}/Magic_seed_detail.png`,
    'Ring of nature': `${WikiItemImages.BASE_URL}/Ring_of_nature.png`,
    'Crystal key': `${WikiItemImages.BASE_URL}/Crystal_key.png`,
    'Lava dragon mask': `${WikiItemImages.BASE_URL}/Lava_dragon_mask.png`,
    'Battlestaff': `${WikiItemImages.BASE_URL}/Battlestaff.png`,
    'Extended antifire(4)': `${WikiItemImages.BASE_URL}/Extended_antifire(4).png`,
    'Super restore(4)': `${WikiItemImages.BASE_URL}/Super_restore(4).png`,
    'Saradomin brew(4)': `${WikiItemImages.BASE_URL}/Saradomin_brew(4).png`,
    'Ranging potion(4)': `${WikiItemImages.BASE_URL}/Ranging_potion(4).png`,
    'Gilded scimitar': `${WikiItemImages.BASE_URL}/Gilded_scimitar.png`,
    'Gilded boots': `${WikiItemImages.BASE_URL}/Gilded_boots.png`,
    'Gilded coif': `${WikiItemImages.BASE_URL}/Gilded_coif.png`,
    'Gilded d\'hide vambraces': `${WikiItemImages.BASE_URL}/Gilded_d'hide_vambraces.png`,
    'Gilded d\'hide body': `${WikiItemImages.BASE_URL}/Gilded_d'hide_body.png`,
    'Gilded d\'hide chaps': `${WikiItemImages.BASE_URL}/Gilded_d'hide_chaps.png`,
    'Gilded pickaxe': `${WikiItemImages.BASE_URL}/Gilded_pickaxe.png`,
    'Gilded axe': `${WikiItemImages.BASE_URL}/Gilded_axe.png`,
    'Gilded spade': `${WikiItemImages.BASE_URL}/Gilded_spade.png`,
    'Gilded full helm': `${WikiItemImages.BASE_URL}/Gilded_full_helm.png`,
    'Gilded platebody': `${WikiItemImages.BASE_URL}/Gilded_platebody.png`,
    'Gilded platelegs': `${WikiItemImages.BASE_URL}/Gilded_platelegs.png`,
    'Gilded plateskirt': `${WikiItemImages.BASE_URL}/Gilded_plateskirt.png`,
    'Gilded kiteshield': `${WikiItemImages.BASE_URL}/Gilded_kiteshield.png`,
    'Gilded med helm': `${WikiItemImages.BASE_URL}/Gilded_med_helm.png`,
    'Gilded chainbody': `${WikiItemImages.BASE_URL}/Gilded_chainbody.png`,
    'Gilded sq shield': `${WikiItemImages.BASE_URL}/Gilded_sq_shield.png`,
    'Gilded 2h sword': `${WikiItemImages.BASE_URL}/Gilded_2h_sword.png`,
    'Gilded spear': `${WikiItemImages.BASE_URL}/Gilded_spear.png`,
    'Gilded hasta': `${WikiItemImages.BASE_URL}/Gilded_hasta.png`,
    '3rd age full helmet': `${WikiItemImages.BASE_URL}/3rd_age_full_helmet.png`,
    '3rd age platebody': `${WikiItemImages.BASE_URL}/3rd_age_platebody.png`,
    '3rd age platelegs': `${WikiItemImages.BASE_URL}/3rd_age_platelegs.png`,
    '3rd age plateskirt': `${WikiItemImages.BASE_URL}/3rd_age_plateskirt.png`,
    '3rd age kiteshield': `${WikiItemImages.BASE_URL}/3rd_age_kiteshield.png`,
    '3rd age range coif': `${WikiItemImages.BASE_URL}/3rd_age_range_coif.png`,
    '3rd age range top': `${WikiItemImages.BASE_URL}/3rd_age_range_top.png`,
    '3rd age range legs': `${WikiItemImages.BASE_URL}/3rd_age_range_legs.png`,
    '3rd age vambraces': `${WikiItemImages.BASE_URL}/3rd_age_vambraces.png`,
    '3rd age mage hat': `${WikiItemImages.BASE_URL}/3rd_age_mage_hat.png`,
    '3rd age robe top': `${WikiItemImages.BASE_URL}/3rd_age_robe_top.png`,
    '3rd age robe': `${WikiItemImages.BASE_URL}/3rd_age_robe.png`,
    '3rd age amulet': `${WikiItemImages.BASE_URL}/3rd_age_amulet.png`,
    '3rd age longsword': `${WikiItemImages.BASE_URL}/3rd_age_longsword.png`,
    '3rd age wand': `${WikiItemImages.BASE_URL}/3rd_age_wand.png`,
    '3rd age cloak': `${WikiItemImages.BASE_URL}/3rd_age_cloak.png`,
    '3rd age bow': `${WikiItemImages.BASE_URL}/3rd_age_bow.png`,
    'Coins (20k-30k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (9-23)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Coins (10k-15k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (8-12)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Red firelighter': `${WikiItemImages.BASE_URL}/Red_firelighter.png`,
    'Green firelighter': `${WikiItemImages.BASE_URL}/Green_firelighter.png`,
    'Blue firelighter': `${WikiItemImages.BASE_URL}/Blue_firelighter.png`,
    'Purple firelighter': `${WikiItemImages.BASE_URL}/Purple_firelighter.png`,
    'White firelighter': `${WikiItemImages.BASE_URL}/White_firelighter.png`,
    'Charge dragonstone jewellery scroll': `${WikiItemImages.BASE_URL}/Charge_dragonstone_jewellery_scroll.png`,
    'Nardah teleport': `${WikiItemImages.BASE_URL}/Nardah_teleport.png`,
    'Mos le\'harmless teleport': `${WikiItemImages.BASE_URL}/Mos_le'harmless_teleport.png`,
    'Mort\'ton teleport': `${WikiItemImages.BASE_URL}/Mort'ton_teleport.png`,
    'Feldip hills teleport': `${WikiItemImages.BASE_URL}/Feldip_hills_teleport.png`,
    'Lunar isle teleport': `${WikiItemImages.BASE_URL}/Lunar_isle_teleport.png`,
    'Digsite teleport': `${WikiItemImages.BASE_URL}/Digsite_teleport.png`,
    'Piscatoris teleport': `${WikiItemImages.BASE_URL}/Piscatoris_teleport.png`,
    'Pest control teleport': `${WikiItemImages.BASE_URL}/Pest_control_teleport.png`,
    'Tai bwo wannai teleport': `${WikiItemImages.BASE_URL}/Tai_bwo_wannai_teleport.png`,
    'Lumberyard teleport': `${WikiItemImages.BASE_URL}/Lumberyard_teleport.png`,
    'Iorwerth camp teleport': `${WikiItemImages.BASE_URL}/Iorwerth_camp_teleport.png`,
    'Master scroll book (empty)': `${WikiItemImages.BASE_URL}/Master_scroll_book_(empty).png`,
    'Holy blessing': `${WikiItemImages.BASE_URL}/Holy_blessing.png`,
    'Unholy blessing': `${WikiItemImages.BASE_URL}/Unholy_blessing.png`,
    'Peaceful blessing': `${WikiItemImages.BASE_URL}/Peaceful_blessing.png`,
    'War blessing': `${WikiItemImages.BASE_URL}/War_blessing.png`,
    'Honourable blessing': `${WikiItemImages.BASE_URL}/Honourable_blessing.png`,
    'Ancient blessing': `${WikiItemImages.BASE_URL}/Ancient_blessing.png`,
    'Saradomin page 1': `${WikiItemImages.BASE_URL}/Saradomin_page_1.png`,
    'Saradomin page 2': `${WikiItemImages.BASE_URL}/Saradomin_page_2.png`,
    'Saradomin page 3': `${WikiItemImages.BASE_URL}/Saradomin_page_3.png`,
    'Saradomin page 4': `${WikiItemImages.BASE_URL}/Saradomin_page_4.png`,
    'Zamorak page 1': `${WikiItemImages.BASE_URL}/Zamorak_page_1.png`,
    'Zamorak page 2': `${WikiItemImages.BASE_URL}/Zamorak_page_2.png`,
    'Zamorak page 3': `${WikiItemImages.BASE_URL}/Zamorak_page_3.png`,
    'Zamorak page 4': `${WikiItemImages.BASE_URL}/Zamorak_page_4.png`,
    'Guthix page 1': `${WikiItemImages.BASE_URL}/Guthix_page_1.png`,
    'Guthix page 2': `${WikiItemImages.BASE_URL}/Guthix_page_2.png`,
    'Guthix page 3': `${WikiItemImages.BASE_URL}/Guthix_page_3.png`,
    'Guthix page 4': `${WikiItemImages.BASE_URL}/Guthix_page_4.png`,
    'Bandos page 1': `${WikiItemImages.BASE_URL}/Bandos_page_1.png`,
    'Bandos page 2': `${WikiItemImages.BASE_URL}/Bandos_page_2.png`,
    'Bandos page 3': `${WikiItemImages.BASE_URL}/Bandos_page_3.png`,
    'Bandos page 4': `${WikiItemImages.BASE_URL}/Bandos_page_4.png`,
    'Armadyl page 1': `${WikiItemImages.BASE_URL}/Armadyl_page_1.png`,
    'Armadyl page 2': `${WikiItemImages.BASE_URL}/Armadyl_page_2.png`,
    'Armadyl page 3': `${WikiItemImages.BASE_URL}/Armadyl_page_3.png`,
    'Armadyl page 4': `${WikiItemImages.BASE_URL}/Armadyl_page_4.png`,
    'Ancient page 1': `${WikiItemImages.BASE_URL}/Ancient_page_1.png`,
    'Ancient page 2': `${WikiItemImages.BASE_URL}/Ancient_page_2.png`,
    'Ancient page 3': `${WikiItemImages.BASE_URL}/Ancient_page_3.png`,
    'Ancient page 4': `${WikiItemImages.BASE_URL}/Ancient_page_4.png`,
    'Clue scroll (master)': `${WikiItemImages.BASE_URL}/Clue_scroll_(master).png`,
  };

  /** Master clue scroll rewards (173 items). */
  static readonly MASTER: Record<string, string> = {
    'Occult ornament kit': `${WikiItemImages.BASE_URL}/Occult_ornament_kit.png`,
    'Torture ornament kit': `${WikiItemImages.BASE_URL}/Torture_ornament_kit.png`,
    'Anguish ornament kit': `${WikiItemImages.BASE_URL}/Anguish_ornament_kit.png`,
    'Tormented ornament kit': `${WikiItemImages.BASE_URL}/Tormented_ornament_kit.png`,
    'Dragon defender ornament kit': `${WikiItemImages.BASE_URL}/Dragon_defender_ornament_kit.png`,
    'Hood of darkness': `${WikiItemImages.BASE_URL}/Hood_of_darkness.png`,
    'Robe top of darkness': `${WikiItemImages.BASE_URL}/Robe_top_of_darkness.png`,
    'Gloves of darkness': `${WikiItemImages.BASE_URL}/Gloves_of_darkness.png`,
    'Robe bottom of darkness': `${WikiItemImages.BASE_URL}/Robe_bottom_of_darkness.png`,
    'Boots of darkness': `${WikiItemImages.BASE_URL}/Boots_of_darkness.png`,
    'Samurai kasa': `${WikiItemImages.BASE_URL}/Samurai_kasa.png`,
    'Samurai shirt': `${WikiItemImages.BASE_URL}/Samurai_shirt.png`,
    'Samurai gloves': `${WikiItemImages.BASE_URL}/Samurai_gloves.png`,
    'Samurai greaves': `${WikiItemImages.BASE_URL}/Samurai_greaves.png`,
    'Samurai boots': `${WikiItemImages.BASE_URL}/Samurai_boots.png`,
    'Arceuus hood': `${WikiItemImages.BASE_URL}/Arceuus_hood.png`,
    'Hosidius hood': `${WikiItemImages.BASE_URL}/Hosidius_hood.png`,
    'Lovakengj hood': `${WikiItemImages.BASE_URL}/Lovakengj_hood.png`,
    'Piscarilius hood': `${WikiItemImages.BASE_URL}/Piscarilius_hood.png`,
    'Shayzien hood': `${WikiItemImages.BASE_URL}/Shayzien_hood.png`,
    'Old demon mask': `${WikiItemImages.BASE_URL}/Old_demon_mask.png`,
    'Lesser demon mask': `${WikiItemImages.BASE_URL}/Lesser_demon_mask.png`,
    'Greater demon mask': `${WikiItemImages.BASE_URL}/Greater_demon_mask.png`,
    'Black demon mask': `${WikiItemImages.BASE_URL}/Black_demon_mask.png`,
    'Jungle demon mask': `${WikiItemImages.BASE_URL}/Jungle_demon_mask.png`,
    'Left eye patch': `${WikiItemImages.BASE_URL}/Left_eye_patch.png`,
    'Bowl wig': `${WikiItemImages.BASE_URL}/Bowl_wig.png`,
    'Ale of the gods': `${WikiItemImages.BASE_URL}/Ale_of_the_gods.png`,
    'Obsidian cape (r)': `${WikiItemImages.BASE_URL}/Obsidian_cape_(r).png`,
    'Fancy tiara': `${WikiItemImages.BASE_URL}/Fancy_tiara.png`,
    'Half moon spectacles': `${WikiItemImages.BASE_URL}/Half_moon_spectacles.png`,
    'Armadyl godsword ornament kit': `${WikiItemImages.BASE_URL}/Armadyl_godsword_ornament_kit.png`,
    'Bandos godsword ornament kit': `${WikiItemImages.BASE_URL}/Bandos_godsword_ornament_kit.png`,
    'Saradomin godsword ornament kit': `${WikiItemImages.BASE_URL}/Saradomin_godsword_ornament_kit.png`,
    'Zamorak godsword ornament kit': `${WikiItemImages.BASE_URL}/Zamorak_godsword_ornament_kit.png`,
    'Dragon platebody ornament kit': `${WikiItemImages.BASE_URL}/Dragon_platebody_ornament_kit.png`,
    'Ankou mask': `${WikiItemImages.BASE_URL}/Ankou_mask.png`,
    'Ankou top': `${WikiItemImages.BASE_URL}/Ankou_top.png`,
    'Ankou gloves': `${WikiItemImages.BASE_URL}/Ankou_gloves.png`,
    'Ankou\'s leggings': `${WikiItemImages.BASE_URL}/Ankou's_leggings.png`,
    'Ankou socks': `${WikiItemImages.BASE_URL}/Ankou_socks.png`,
    'Mummy\'s head': `${WikiItemImages.BASE_URL}/Mummy's_head.png`,
    'Mummy\'s body': `${WikiItemImages.BASE_URL}/Mummy's_body.png`,
    'Mummy\'s hands': `${WikiItemImages.BASE_URL}/Mummy's_hands.png`,
    'Mummy\'s legs': `${WikiItemImages.BASE_URL}/Mummy's_legs.png`,
    'Mummy\'s feet': `${WikiItemImages.BASE_URL}/Mummy's_feet.png`,
    'Dragon kiteshield ornament kit': `${WikiItemImages.BASE_URL}/Dragon_kiteshield_ornament_kit.png`,
    'Dragon dagger': `${WikiItemImages.BASE_URL}/Dragon_dagger.png`,
    'Dragon mace': `${WikiItemImages.BASE_URL}/Dragon_mace.png`,
    'Dragon longsword': `${WikiItemImages.BASE_URL}/Dragon_longsword.png`,
    'Dragon scimitar': `${WikiItemImages.BASE_URL}/Dragon_scimitar.png`,
    'Dragon battleaxe': `${WikiItemImages.BASE_URL}/Dragon_battleaxe.png`,
    'Dragon halberd': `${WikiItemImages.BASE_URL}/Dragon_halberd.png`,
    'Nature rune': `${WikiItemImages.BASE_URL}/Nature_rune.png`,
    'Death rune': `${WikiItemImages.BASE_URL}/Death_rune.png`,
    'Blood rune': `${WikiItemImages.BASE_URL}/Blood_rune.png`,
    'Soul rune': `${WikiItemImages.BASE_URL}/Soul_rune.png`,
    'Onyx bolts (e)': `${WikiItemImages.BASE_URL}/Onyx_bolts_(e)_detail.png`,
    'Manta ray': `${WikiItemImages.BASE_URL}/Manta_ray.png`,
    'Wine of zamorak': `${WikiItemImages.BASE_URL}/Wine_of_zamorak.png`,
    'Limpwurt root': `${WikiItemImages.BASE_URL}/Limpwurt_root.png`,
    'Grimy ranarr weed': `${WikiItemImages.BASE_URL}/Grimy_ranarr_weed.png`,
    'Grimy toadflax': `${WikiItemImages.BASE_URL}/Grimy_toadflax.png`,
    'Grimy snapdragon': `${WikiItemImages.BASE_URL}/Grimy_snapdragon.png`,
    'Runite ore': `${WikiItemImages.BASE_URL}/Runite_ore.png`,
    'Runite bar': `${WikiItemImages.BASE_URL}/Runite_bar.png`,
    'Black dragonhide': `${WikiItemImages.BASE_URL}/Black_dragonhide.png`,
    'Tooth half of key': `${WikiItemImages.BASE_URL}/Tooth_half_of_key.png`,
    'Loop half of key': `${WikiItemImages.BASE_URL}/Loop_half_of_key.png`,
    'Palm tree seed': `${WikiItemImages.BASE_URL}/Palm_tree_seed_detail.png`,
    'Yew seed': `${WikiItemImages.BASE_URL}/Yew_seed_detail.png`,
    'Magic seed': `${WikiItemImages.BASE_URL}/Magic_seed_detail.png`,
    'Bucket helm (g)': `${WikiItemImages.BASE_URL}/Bucket_helm_(g).png`,
    'Ring of coins': `${WikiItemImages.BASE_URL}/Ring_of_coins.png`,
    'Cabbage': `${WikiItemImages.BASE_URL}/Cabbage.png`,
    'Anti-venom+(4)': `${WikiItemImages.BASE_URL}/Anti-venom+(4).png`,
    'Torstol': `${WikiItemImages.BASE_URL}/Torstol.png`,
    'Gilded scimitar': `${WikiItemImages.BASE_URL}/Gilded_scimitar.png`,
    'Gilded boots': `${WikiItemImages.BASE_URL}/Gilded_boots.png`,
    'Gilded coif': `${WikiItemImages.BASE_URL}/Gilded_coif.png`,
    'Gilded d\'hide vambraces': `${WikiItemImages.BASE_URL}/Gilded_d'hide_vambraces.png`,
    'Gilded d\'hide body': `${WikiItemImages.BASE_URL}/Gilded_d'hide_body.png`,
    'Gilded d\'hide chaps': `${WikiItemImages.BASE_URL}/Gilded_d'hide_chaps.png`,
    'Gilded pickaxe': `${WikiItemImages.BASE_URL}/Gilded_pickaxe.png`,
    'Gilded axe': `${WikiItemImages.BASE_URL}/Gilded_axe.png`,
    'Gilded spade': `${WikiItemImages.BASE_URL}/Gilded_spade.png`,
    'Gilded full helm': `${WikiItemImages.BASE_URL}/Gilded_full_helm.png`,
    'Gilded platebody': `${WikiItemImages.BASE_URL}/Gilded_platebody.png`,
    'Gilded platelegs': `${WikiItemImages.BASE_URL}/Gilded_platelegs.png`,
    'Gilded plateskirt': `${WikiItemImages.BASE_URL}/Gilded_plateskirt.png`,
    'Gilded kiteshield': `${WikiItemImages.BASE_URL}/Gilded_kiteshield.png`,
    'Gilded med helm': `${WikiItemImages.BASE_URL}/Gilded_med_helm.png`,
    'Gilded chainbody': `${WikiItemImages.BASE_URL}/Gilded_chainbody.png`,
    'Gilded sq shield': `${WikiItemImages.BASE_URL}/Gilded_sq_shield.png`,
    'Gilded 2h sword': `${WikiItemImages.BASE_URL}/Gilded_2h_sword.png`,
    'Gilded spear': `${WikiItemImages.BASE_URL}/Gilded_spear.png`,
    'Gilded hasta': `${WikiItemImages.BASE_URL}/Gilded_hasta.png`,
    '3rd age full helmet': `${WikiItemImages.BASE_URL}/3rd_age_full_helmet.png`,
    '3rd age platebody': `${WikiItemImages.BASE_URL}/3rd_age_platebody.png`,
    '3rd age platelegs': `${WikiItemImages.BASE_URL}/3rd_age_platelegs.png`,
    '3rd age plateskirt': `${WikiItemImages.BASE_URL}/3rd_age_plateskirt.png`,
    '3rd age kiteshield': `${WikiItemImages.BASE_URL}/3rd_age_kiteshield.png`,
    '3rd age range coif': `${WikiItemImages.BASE_URL}/3rd_age_range_coif.png`,
    '3rd age range top': `${WikiItemImages.BASE_URL}/3rd_age_range_top.png`,
    '3rd age range legs': `${WikiItemImages.BASE_URL}/3rd_age_range_legs.png`,
    '3rd age vambraces': `${WikiItemImages.BASE_URL}/3rd_age_vambraces.png`,
    '3rd age mage hat': `${WikiItemImages.BASE_URL}/3rd_age_mage_hat.png`,
    '3rd age robe top': `${WikiItemImages.BASE_URL}/3rd_age_robe_top.png`,
    '3rd age robe': `${WikiItemImages.BASE_URL}/3rd_age_robe.png`,
    '3rd age amulet': `${WikiItemImages.BASE_URL}/3rd_age_amulet.png`,
    '3rd age druidic robe top': `${WikiItemImages.BASE_URL}/3rd_age_druidic_robe_top.png`,
    '3rd age druidic robe bottoms': `${WikiItemImages.BASE_URL}/3rd_age_druidic_robe_bottoms.png`,
    '3rd age druidic cloak': `${WikiItemImages.BASE_URL}/3rd_age_druidic_cloak.png`,
    '3rd age longsword': `${WikiItemImages.BASE_URL}/3rd_age_longsword.png`,
    '3rd age bow': `${WikiItemImages.BASE_URL}/3rd_age_bow.png`,
    '3rd age wand': `${WikiItemImages.BASE_URL}/3rd_age_wand.png`,
    '3rd age druidic staff': `${WikiItemImages.BASE_URL}/3rd_age_druidic_staff.png`,
    '3rd age cloak': `${WikiItemImages.BASE_URL}/3rd_age_cloak.png`,
    '3rd age pickaxe': `${WikiItemImages.BASE_URL}/3rd_age_pickaxe.png`,
    '3rd age axe': `${WikiItemImages.BASE_URL}/3rd_age_axe.png`,
    'Coins (20k-35k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (14-33)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Coins (10k-15k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Purple sweets (8-12)': `${WikiItemImages.BASE_URL}/Purple_sweets_detail.png`,
    'Red firelighter': `${WikiItemImages.BASE_URL}/Red_firelighter.png`,
    'Green firelighter': `${WikiItemImages.BASE_URL}/Green_firelighter.png`,
    'Blue firelighter': `${WikiItemImages.BASE_URL}/Blue_firelighter.png`,
    'Purple firelighter': `${WikiItemImages.BASE_URL}/Purple_firelighter.png`,
    'White firelighter': `${WikiItemImages.BASE_URL}/White_firelighter.png`,
    'Charge dragonstone jewellery scroll': `${WikiItemImages.BASE_URL}/Charge_dragonstone_jewellery_scroll.png`,
    'Nardah teleport': `${WikiItemImages.BASE_URL}/Nardah_teleport.png`,
    'Mos le\'harmless teleport': `${WikiItemImages.BASE_URL}/Mos_le'harmless_teleport.png`,
    'Mort\'ton teleport': `${WikiItemImages.BASE_URL}/Mort'ton_teleport.png`,
    'Feldip hills teleport': `${WikiItemImages.BASE_URL}/Feldip_hills_teleport.png`,
    'Lunar isle teleport': `${WikiItemImages.BASE_URL}/Lunar_isle_teleport.png`,
    'Digsite teleport': `${WikiItemImages.BASE_URL}/Digsite_teleport.png`,
    'Piscatoris teleport': `${WikiItemImages.BASE_URL}/Piscatoris_teleport.png`,
    'Pest control teleport': `${WikiItemImages.BASE_URL}/Pest_control_teleport.png`,
    'Tai bwo wannai teleport': `${WikiItemImages.BASE_URL}/Tai_bwo_wannai_teleport.png`,
    'Lumberyard teleport': `${WikiItemImages.BASE_URL}/Lumberyard_teleport.png`,
    'Iorwerth camp teleport': `${WikiItemImages.BASE_URL}/Iorwerth_camp_teleport.png`,
    'Master scroll book (empty)': `${WikiItemImages.BASE_URL}/Master_scroll_book_(empty).png`,
    'Coins (15k-30k)': `${WikiItemImages.BASE_URL}/Coins_detail.png`,
    'Holy blessing': `${WikiItemImages.BASE_URL}/Holy_blessing.png`,
    'Unholy blessing': `${WikiItemImages.BASE_URL}/Unholy_blessing.png`,
    'Peaceful blessing': `${WikiItemImages.BASE_URL}/Peaceful_blessing.png`,
    'War blessing': `${WikiItemImages.BASE_URL}/War_blessing.png`,
    'Honourable blessing': `${WikiItemImages.BASE_URL}/Honourable_blessing.png`,
    'Ancient blessing': `${WikiItemImages.BASE_URL}/Ancient_blessing.png`,
    'Saradomin page 1': `${WikiItemImages.BASE_URL}/Saradomin_page_1.png`,
    'Saradomin page 2': `${WikiItemImages.BASE_URL}/Saradomin_page_2.png`,
    'Saradomin page 3': `${WikiItemImages.BASE_URL}/Saradomin_page_3.png`,
    'Saradomin page 4': `${WikiItemImages.BASE_URL}/Saradomin_page_4.png`,
    'Zamorak page 1': `${WikiItemImages.BASE_URL}/Zamorak_page_1.png`,
    'Zamorak page 2': `${WikiItemImages.BASE_URL}/Zamorak_page_2.png`,
    'Zamorak page 3': `${WikiItemImages.BASE_URL}/Zamorak_page_3.png`,
    'Zamorak page 4': `${WikiItemImages.BASE_URL}/Zamorak_page_4.png`,
    'Guthix page 1': `${WikiItemImages.BASE_URL}/Guthix_page_1.png`,
    'Guthix page 2': `${WikiItemImages.BASE_URL}/Guthix_page_2.png`,
    'Guthix page 3': `${WikiItemImages.BASE_URL}/Guthix_page_3.png`,
    'Guthix page 4': `${WikiItemImages.BASE_URL}/Guthix_page_4.png`,
    'Bandos page 1': `${WikiItemImages.BASE_URL}/Bandos_page_1.png`,
    'Bandos page 2': `${WikiItemImages.BASE_URL}/Bandos_page_2.png`,
    'Bandos page 3': `${WikiItemImages.BASE_URL}/Bandos_page_3.png`,
    'Bandos page 4': `${WikiItemImages.BASE_URL}/Bandos_page_4.png`,
    'Armadyl page 1': `${WikiItemImages.BASE_URL}/Armadyl_page_1.png`,
    'Armadyl page 2': `${WikiItemImages.BASE_URL}/Armadyl_page_2.png`,
    'Armadyl page 3': `${WikiItemImages.BASE_URL}/Armadyl_page_3.png`,
    'Armadyl page 4': `${WikiItemImages.BASE_URL}/Armadyl_page_4.png`,
    'Ancient page 1': `${WikiItemImages.BASE_URL}/Ancient_page_1.png`,
    'Ancient page 2': `${WikiItemImages.BASE_URL}/Ancient_page_2.png`,
    'Ancient page 3': `${WikiItemImages.BASE_URL}/Ancient_page_3.png`,
    'Ancient page 4': `${WikiItemImages.BASE_URL}/Ancient_page_4.png`,
  };

  /** Looks up a clue scroll reward image by its exact item name, across every tier. */
  static getClueItemImage(name: string): string | undefined {
    return (
      WikiItemImages.BEGINNER[name] ??
      WikiItemImages.EASY[name] ??
      WikiItemImages.MEDIUM[name] ??
      WikiItemImages.HARD[name] ??
      WikiItemImages.ELITE[name] ??
      WikiItemImages.MASTER[name]
    );
  }
}
